package com.repodna.scanner.model;

import java.nio.file.Path;
import java.util.List;

/**
 * Immutable container aggregating all outputs generated by the Repository Scanner.
 */
public record ScannerResult(
    String repoName,
    Path repoPath,
    GitInfo gitInfo,
    List<LanguageInfo> languages,
    LanguageInfo primaryLanguage,
    List<FrameworkInfo> frameworks,
    BuildSystemInfo buildSystem,
    RepositoryStatistics stats,
    DocumentationInfo documentation,
    List<String> configs
) {}
